# -*- coding: utf-8 -*-
"""開源社01.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10Tk5E9v6W03FvXBx-0pj6iHRMUJu4iXH
"""

print('hello world')

fruits = ['a','b']
for i in fruits:
  print(i)

import random
answer = random.randint(1000,9999)
print(answer)
answer = str(answer)
#answer = "1234"
while(True):
    while(True):
      user = input("請輸入你的答案 4位數")
      user = str(user)  
      if len(user) == 4 :
        break
      else :
        print("輸入正確四位數")     
    A = 0
    B = 4
    for i in range(4):
       if answer[i] == user[i]:
          A += 1
    if A == 4 :
      break
    else:
      B = B - A
      print(A,"A",B,"B")
print("恭喜你猜中了")